backend:
  name: git-gateway
  branch: main          # or master if your default branch is master

media_folder: "images/uploads"   # where uploaded files go inside repo
public_folder: "/images/uploads" # how those files are accessed in site

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"       # 👈 create this folder in your repo
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
